version: '3.7'
services:
    postgres:
        image: postgres:10.13
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: dangkv/docker-airflow:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    scheduler:
            image: dangkv/docker-airflow:latest
            restart: always
            depends_on:
                - webserver
                - postgres
            logging:
                options:
                    max-size: 10m
                    max-file: "3"
            volumes:
                - ./dags:/usr/local/airflow/dags
                - ./plugins:/usr/local/airflow/plugins
            environment:
                - LOAD_EX=n
                - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
                - EXECUTOR=Local
            command: scheduler
